export const dailySliderProps = {
  dotSize: 28,
  width: 'auto',
  height: 2,
  contained: true, // false
  direction: 'ltr',
  data: null,
  dataLabel: 'label',
  dataValue: 'value',
  min: 0,
  max: 1440,
  interval: 30,
  disabled: false,
  clickable: false,
  dragOnClick: false,
  duration: 0.1,
  adsorb: false,
  lazy: false,
  tooltip: 'none',
  tooltipFormatter: void 0,
  useKeyboard: false,
  keydownHook: null,
  enableCross: false,
  fixed: false,
  minRange: 30,
  maxRange: void 0,
  order: true,
  marks: false,
  included: false,
  dotOptions: void 0,
  dotAttrs: void 0,
  process: false,
  dotStyle: void 0,
  railStyle: { 'background-color': 'var(--secondary20)' },
  processStyle: void 0,
  tooltipStyle: void 0,
  stepStyle: void 0,
  stepActiveStyle: void 0,
  labelStyle: void 0,
  labelActiveStyle: void 0,
}
